"""Stimulus-corpus engine (Task E1, by design, R4).

Two public engine functions over the pinned, checksummed stimulus corpus:

- :func:`list_items` — read ``corpus/manifest.toml`` into structured
  :class:`CorpusItem` records (name, path, kind, generator, sha256, params).
- :func:`verify` — recompute each item's sha256 and compare against the manifest,
  returning a **structured** :class:`VerifyResult` (pass/failure), never a CLI
  exit code. The CLI nonzero-exit mapping for ``corpus verify`` is H1's job
  (CLI-wiring boundary I6); this module does NOT touch ``cli.py``.

The corpus items themselves are script-generated by ``scripts/generate_corpus.py``
(byte-identical, pinned RNG seed). This module only reads the manifest and hashes
files on disk — it never regenerates.
"""

from __future__ import annotations

import hashlib
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional

# --- Locations (repo layout: src/sonoscope/corpus.py -> repo root at [2]) -----
_REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_CORPUS_ROOT = _REPO_ROOT / "corpus"
DEFAULT_MANIFEST = DEFAULT_CORPUS_ROOT / "manifest.toml"

# Machine-readable failure reasons on an item verification (exact strings; the
# tests and any downstream consumer key on these verbatim).
REASON_MISSING = "missing"
REASON_HASH_MISMATCH = "hash-mismatch"

_HASH_CHUNK = 1 << 20  # 1 MiB streaming read


@dataclass(frozen=True)
class CorpusItem:
    """One pinned corpus item as recorded in the manifest."""

    name: str
    path: str  # corpus-root-relative, e.g. "signals/tone_1k_2s.wav"
    kind: str  # "signal" | "midi"
    generator: str
    sha256: str
    params: dict[str, Any]


@dataclass(frozen=True)
class ItemVerification:
    """Result of verifying one item's on-disk bytes against the manifest."""

    name: str
    path: str
    expected_sha256: str
    actual_sha256: Optional[str]  # None when the file is missing
    ok: bool
    reason: Optional[str]  # None when ok; else REASON_MISSING / REASON_HASH_MISMATCH


@dataclass(frozen=True)
class VerifyResult:
    """Structured whole-corpus verify verdict (pass/failure, not an exit code)."""

    ok: bool
    items: tuple[ItemVerification, ...]

    @property
    def failures(self) -> tuple[ItemVerification, ...]:
        """Only the items that failed verification (empty when ``ok``)."""
        return tuple(item for item in self.items if not item.ok)


def _load_manifest(manifest_path: Path) -> dict[str, Any]:
    with open(manifest_path, "rb") as handle:
        return tomllib.load(handle)


def list_items(manifest_path: Path = DEFAULT_MANIFEST) -> list[CorpusItem]:
    """Parse the manifest into :class:`CorpusItem` records (manifest order).

    ``dict`` preserves insertion order, so items are returned in the order the
    generator wrote them into the manifest.
    """
    manifest = _load_manifest(Path(manifest_path))
    items_table = manifest.get("items", {})
    items: list[CorpusItem] = []
    for name, entry in items_table.items():
        items.append(
            CorpusItem(
                name=name,
                path=entry["path"],
                kind=entry["kind"],
                generator=entry["generator"],
                sha256=entry["sha256"],
                params=dict(entry.get("params", {})),
            )
        )
    return items


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(_HASH_CHUNK), b""):
            digest.update(chunk)
    return digest.hexdigest()


def verify(
    corpus_root: Path = DEFAULT_CORPUS_ROOT,
    manifest_path: Path = DEFAULT_MANIFEST,
) -> VerifyResult:
    """Recompute every item's sha256 and compare against the manifest.

    Returns a structured :class:`VerifyResult`: ``ok`` is ``True`` only when every
    manifest item is present and its bytes hash exactly to the pinned value. A
    missing file yields ``reason=REASON_MISSING`` (``actual_sha256=None``); a hash
    drift yields ``reason=REASON_HASH_MISMATCH``. This never raises on drift and
    never returns an exit code — the CLI mapping is H1's (I6).
    """
    corpus_root = Path(corpus_root)
    verifications: list[ItemVerification] = []
    for item in list_items(manifest_path):
        file_path = corpus_root / item.path
        if not file_path.is_file():
            verifications.append(
                ItemVerification(
                    name=item.name,
                    path=item.path,
                    expected_sha256=item.sha256,
                    actual_sha256=None,
                    ok=False,
                    reason=REASON_MISSING,
                )
            )
            continue
        actual = _sha256_file(file_path)
        if actual == item.sha256:
            verifications.append(
                ItemVerification(
                    name=item.name,
                    path=item.path,
                    expected_sha256=item.sha256,
                    actual_sha256=actual,
                    ok=True,
                    reason=None,
                )
            )
        else:
            verifications.append(
                ItemVerification(
                    name=item.name,
                    path=item.path,
                    expected_sha256=item.sha256,
                    actual_sha256=actual,
                    ok=False,
                    reason=REASON_HASH_MISMATCH,
                )
            )

    overall_ok = all(v.ok for v in verifications) and len(verifications) > 0
    return VerifyResult(ok=overall_ok, items=tuple(verifications))
